version: '3'
networks:
  howdy:
    driver: bridge

services:
  discovery:
    image: eureka
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - howdy
  newsfeed:
    image: newsfeed
    build:
      context: ./howdy-newsfeed
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - howdy