server:
  port: 8090

spring:
  application:
    name: api-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

ribbon:
  ReadTimeout: 1000000

zuul:
  host:
    connect-timeout-millis: 1000000
    socket-timeout-millis: 1000000
  routes:
    user-service:
      sensitiveHeaders:
      path: /user-service/**
      serviceId: user-service
      stripPrefix: true
