package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.repository.KomentarRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller // This means that this class is a Controller
@RequestMapping(path="/komentar") // This means URL's start with /demo (after Application path)
public class KomentarController {
    @Autowired // This means to get the bean called statusRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private KomentarRepository komentarRepository;
}
