package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.repository.PostRepository;
import com.example.accessingdatamysql.model.Post;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/post") // This means URL's start with /demo (after Application path)
public class PostController {
    @Autowired // This means to get the bean called statusRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PostRepository postRepository;



    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addPost(@RequestParam String text
            , @RequestParam Long userId) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Post n = new Post(text, userId);

        postRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Post> getAllstatuss() {
        // This returns a JSON or XML with the statuss
        return postRepository.findAll();
    }
}