package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.repository.StatusRepository;
import com.example.accessingdatamysql.model.Status;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/status") // This means URL's start with /demo (after Application path)
public class StatusController {
    @Autowired // This means to get the bean called statusRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StatusRepository statusRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewstatus (@RequestParam String text
            , @RequestParam Integer userId) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Status n = new Status();
        n.setText(text);
        n.setUserId(userId);
        statusRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Status> getAllstatuss() {
        // This returns a JSON or XML with the statuss
        return statusRepository.findAll();
    }
}